# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sdm660-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter lavender_4.19,$(TARGET_DEVICE)),)

endif
